/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estocmed.telas;

import estocmed.curso.Curso;
import estocmed.curso.CursoDAO;
import estocmed.curso.CursoTableModel;
import estocmed.estoqueconsumo.EstoqueConsumo;
import estocmed.estoqueconsumo.EstoqueConsumoDAO;
import estocmed.estoqueconsumo.EstoqueConsumoTableModel;
import estocmed.produtoconsumo.ProdutoConsumo;
import estocmed.produtoconsumo.ProdutoConsumoDAO;
import estocmed.produtoconsumo.ProdutoConsumoTableModel;
import estocmed.usuario.Usuario;
import estocmed.util.Util;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriano Lima
 */
public class CadastroEstoqueConsumo extends javax.swing.JDialog {

    EstoqueConsumo estoque = new EstoqueConsumo();
    EstoqueConsumoDAO estoqueDAO;
    ProdutoConsumo produto = new ProdutoConsumo();
    ProdutoConsumoDAO produtoDAO;
    Usuario usuario = new Usuario();
    Curso curso = new Curso();
    CursoDAO cursoDAO;
    SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form TelaCadastroUsuario
     *
     * @param usuario
     */
    public CadastroEstoqueConsumo(java.awt.Frame parent, boolean modal, Usuario usuario) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);
        btLimparActionPerformed(null);
        setModal(true);
        txtProduto.setEnabled(false);
        txtCurso.setEnabled(false);
        this.usuario = usuario;
        produtoDAO = new ProdutoConsumoDAO(this.usuario);
        estoqueDAO = new EstoqueConsumoDAO(this.usuario);
        cursoDAO = new CursoDAO(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDestino = new javax.swing.ButtonGroup();
        jlNomeUsuario6 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLObrigatorioNome4 = new javax.swing.JLabel();
        btnCurso = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jLObrigatorioNome = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jlNomeUsuario1 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlNomeUsuario3 = new javax.swing.JLabel();
        txtVencimento = new javax.swing.JFormattedTextField();
        jLObrigatorioNome2 = new javax.swing.JLabel();
        jrLaboratorio = new javax.swing.JRadioButton();
        jrEstagio = new javax.swing.JRadioButton();
        jlNomeUsuario5 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnProduto2 = new javax.swing.JButton();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(602, 421));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Curso:");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(60, 140, 70, 20);

        txtCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtCurso.setMaximumSize(new java.awt.Dimension(8, 200));
        txtCurso.setMinimumSize(new java.awt.Dimension(8, 200));
        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCurso);
        txtCurso.setBounds(60, 160, 450, 30);

        jLObrigatorioNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome4.setText("*");
        getContentPane().add(jLObrigatorioNome4);
        jLObrigatorioNome4.setBounds(510, 160, 10, 20);

        btnCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnCurso.setContentAreaFilled(false);
        btnCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCurso);
        btnCurso.setBounds(520, 160, 30, 30);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setDefaultCapable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(20, 340, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(260, 340, 100, 73);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(370, 340, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(160, 340, 80, 70);

        jLObrigatorioNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome.setText("*");
        getContentPane().add(jLObrigatorioNome);
        jLObrigatorioNome.setBounds(510, 220, 9, 20);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/Salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(500, 340, 80, 70);

        jlNomeUsuario1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario1.setText("Quantidade:");
        getContentPane().add(jlNomeUsuario1);
        jlNomeUsuario1.setBounds(400, 200, 100, 20);

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtQuantidade.setMaximumSize(new java.awt.Dimension(8, 200));
        txtQuantidade.setMinimumSize(new java.awt.Dimension(8, 200));
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(400, 220, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Tipo Entrada:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 270, 100, 19);

        jlNomeUsuario3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario3.setText("Vencimento:");
        getContentPane().add(jlNomeUsuario3);
        jlNomeUsuario3.setBounds(60, 200, 110, 20);

        txtVencimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        try {
            txtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtVencimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVencimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtVencimento);
        txtVencimento.setBounds(60, 220, 150, 30);

        jLObrigatorioNome2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome2.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome2.setText("*");
        getContentPane().add(jLObrigatorioNome2);
        jLObrigatorioNome2.setBounds(210, 220, 10, 20);

        grupoDestino.add(jrLaboratorio);
        jrLaboratorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrLaboratorio.setText("Laboratório");
        getContentPane().add(jrLaboratorio);
        jrLaboratorio.setBounds(280, 270, 120, 23);

        grupoDestino.add(jrEstagio);
        jrEstagio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrEstagio.setText("Estágio");
        getContentPane().add(jrEstagio);
        jrEstagio.setBounds(170, 270, 90, 25);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Produto:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(60, 80, 70, 20);

        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtProduto.setMaximumSize(new java.awt.Dimension(8, 200));
        txtProduto.setMinimumSize(new java.awt.Dimension(8, 200));
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto);
        txtProduto.setBounds(60, 100, 450, 30);

        btnProduto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnProduto2.setContentAreaFilled(false);
        btnProduto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduto2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto2);
        btnProduto2.setBounds(520, 100, 30, 30);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(510, 100, 10, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/EstoqueConsumo.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(2, 0, 600, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<EstoqueConsumo> lista;
        lista = (estoqueDAO.listar());
        EstoqueConsumoTableModel itm = new EstoqueConsumoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Produto");
        if (objetoRetorno != null) {
            estoque = estoqueDAO.consultarObjetoId("idEstoque", objetoRetorno);
            String quantidade = estoque.getQtdEstoque().toString();
            curso = cursoDAO.consultarObjetoId("idCurso", estoque.getCurso().getIdCurso());
            produto = produtoDAO.consultarObjetoId("idProduto", estoque.getProduto().getIdProduto());
            txtQuantidade.setText(quantidade);
            txtVencimento.setText(formatarData.format(estoque.getVencimentoProdConsumo()));
            txtProduto.setText(produto.getNomeProdutoConsumo());
            txtCurso.setText(curso.getNomeCurso());
            if (estoque.getTipoEntrada().equalsIgnoreCase(jrEstagio.getText())) {
                jrEstagio.setSelected(true);
            }
            if (estoque.getTipoEntrada().equalsIgnoreCase(jrLaboratorio.getText())) {
                jrLaboratorio.setSelected(true);
            }

            btExcluir.setEnabled(true);
        }


    }//GEN-LAST:event_btPesquisarActionPerformed

    private String converterDataString(Date date) {
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        return f.format(date);
    }
    
    private Date formataData(String data) {
        if (data == null || data.equals("")) {
            return null;
        }
        Date d = null;
        try {
            DateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
            d = formatar.parse(data);
        } catch (ParseException e) {

        }
        return d;
    }
    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        estoqueDAO.excluir(estoque);
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        btExcluir.setEnabled(false);
        //usuario = new Usuario();

    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (txtProduto.getText().equals("") || txtCurso.getText().equals("") || txtQuantidade.getText().equals("") || txtVencimento.getText().equals("") || !(jrEstagio.isSelected() || jrLaboratorio.isSelected())) {
            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
        } else {
            estoque.setQtdEstoque(Integer.parseInt(txtQuantidade.getText()));
            estoque.setVencimentoProdConsumo(formataData(txtVencimento.getText()));
            if (jrEstagio.isSelected()) {
                estoque.setTipoEntrada(jrEstagio.getText());
            } else if (jrLaboratorio.isSelected()) {
                estoque.setTipoEntrada(jrLaboratorio.getText());
            }
            estoque.setProduto(produto);
            
            estoque.setCurso(curso);
            estoque.setDataEntrada(new Date());
            estoque.setQtdSaida(0);
            estoqueDAO.salvar(estoque);
            grupoDestino.clearSelection();
            btLimparActionPerformed(null);
            estoque = new EstoqueConsumo();

        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void btnProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduto2ActionPerformed
        List<ProdutoConsumo> lista;
        lista = (produtoDAO.listar());
        ProdutoConsumoTableModel itm = new ProdutoConsumoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Produto");
        if (objetoRetorno != null) {
            produto = produtoDAO.consultarObjetoId("idProduto", objetoRetorno);

            txtProduto.setText(produto.getNomeProdutoConsumo());
            txtProduto.setEnabled(false);

        }
    }//GEN-LAST:event_btnProduto2ActionPerformed

    private void txtVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVencimentoActionPerformed

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        List<Curso> lista;
        lista = (cursoDAO.listar());
        CursoTableModel itm = new CursoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Curso");
        if (objetoRetorno != null) {
            curso = cursoDAO.consultarObjetoId("idCurso", objetoRetorno);

            txtCurso.setText(curso.getNomeCurso());
            txtCurso.setEnabled(false);

        }
    }//GEN-LAST:event_btnCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoqueConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroEstoqueConsumo dialog = new CadastroEstoqueConsumo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnProduto2;
    private javax.swing.ButtonGroup grupoDestino;
    private javax.swing.JLabel jLObrigatorioNome;
    private javax.swing.JLabel jLObrigatorioNome2;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlNomeUsuario1;
    private javax.swing.JLabel jlNomeUsuario3;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JRadioButton jrEstagio;
    private javax.swing.JRadioButton jrLaboratorio;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
