/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estocmed.telas;

import estocmed.estoquepermanente.EstoquePermanente;
import estocmed.estoquepermanente.EstoquePermanenteCadastroTableModel;
import estocmed.estoquepermanente.EstoquePermanenteDAO;
import estocmed.estoquepermanente.EstoquePermanenteTableModel;
import estocmed.produtopermanente.ProdutoPermanente;
import estocmed.produtopermanente.ProdutoPermanenteDAO;
import estocmed.produtopermanente.ProdutoPermanenteTableModel;
import estocmed.saidapermanente.SaidaPermanente;
import estocmed.saidapermanente.SaidaPermanenteDAO;
import estocmed.setor.Setor;
import estocmed.setor.SetorDAO;
import estocmed.setor.SetorTableModel;
import estocmed.usuario.Usuario;
import estocmed.util.Util;
import java.awt.Point;
import java.awt.Rectangle;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JViewport;

/**
 *
 * @author Adriano Lima
 */
public class CadastroDevolucaoPermanente extends javax.swing.JDialog {

    EstoquePermanente estoque = new EstoquePermanente();
    EstoquePermanenteDAO estoqueDAO;
    ProdutoPermanente produtoPermanente = new ProdutoPermanente();
    ProdutoPermanenteDAO produtoPermanenteDAO;
    SetorDAO setorDAO;
    Usuario usuario;
    Setor setor = new Setor();
    int qtd;
    int rowEstoque;
    private static Object objeto;
    SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");
    List<EstoquePermanente> listaEstoque = new ArrayList<>();

    /**
     * Creates new form TelaCadastroUsuario
     *
     * @param usuario
     */
    public CadastroDevolucaoPermanente(java.awt.Frame parent, boolean modal, Usuario usuario) {
        initComponents();
        estoqueDAO = new EstoquePermanenteDAO(this.usuario);
        this.usuario = usuario;
        produtoPermanenteDAO = new ProdutoPermanenteDAO(this.usuario);
        setorDAO = new SetorDAO(this.usuario);
        txtProduto.setEnabled(false);
        setModal(true);
    }
    Date date = new Date();
    SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy - hh:mm");

    public void tabelaSaida() {
        EstoquePermanenteTableModel tbl = new EstoquePermanenteTableModel(listaEstoque);
        tbSaida.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDestino = new javax.swing.ButtonGroup();
        jLObrigatorioNome1 = new javax.swing.JLabel();
        jlSaida = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jlNomeUsuario5 = new javax.swing.JLabel();
        btDevolver = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSaida = new javax.swing.JTable();
        btVoltar1 = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLObrigatorioNome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome1.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome1.setText("*");
        getContentPane().add(jLObrigatorioNome1);
        jLObrigatorioNome1.setBounds(600, 80, 10, 30);

        jlSaida.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlSaida.setText("Saída");
        getContentPane().add(jlSaida);
        jlSaida.setBounds(380, 130, 50, 30);

        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtProduto.setMaximumSize(new java.awt.Dimension(8, 200));
        txtProduto.setMinimumSize(new java.awt.Dimension(8, 200));
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto);
        txtProduto.setBounds(220, 90, 380, 30);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Produto:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(150, 90, 70, 30);

        btDevolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/estornar.png"))); // NOI18N
        btDevolver.setText("Devolver");
        btDevolver.setContentAreaFilled(false);
        btDevolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDevolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDevolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolverActionPerformed(evt);
            }
        });
        getContentPane().add(btDevolver);
        btDevolver.setBounds(350, 430, 100, 70);

        btnProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnProduto.setContentAreaFilled(false);
        btnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto);
        btnProduto.setBounds(610, 90, 30, 30);

        tbSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSaida);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 730, 250);

        btVoltar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar1.setText("Voltar");
        btVoltar1.setContentAreaFilled(false);
        btVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar1);
        btVoltar1.setBounds(20, 430, 90, 70);

        btSalvar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/SalvarM.png"))); // NOI18N
        btSalvar1.setText("Salvar");
        btSalvar1.setContentAreaFilled(false);
        btSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar1);
        btSalvar1.setBounds(700, 430, 80, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/devolucaoPermanente.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(800, 520));
        jLabel6.setMinimumSize(new java.awt.Dimension(800, 520));
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltar1ActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        if (produtoPermanente.getIdProdutoPermanente() != 0) {
            for (EstoquePermanente estoquePermanente : listaEstoque) {
                estoqueDAO.atualizar(estoquePermanente);
            }
            JOptionPane.showMessageDialog(null, "Devolução realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não é possível fazer a devolução. Selecione o Produto.");
        }
        limparCampos();
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void limparCampos() {
        Util.limparCamposGenerico(this);
        estoque = new EstoquePermanente();
        produtoPermanente = new ProdutoPermanente();
        listaEstoque = new ArrayList<>();
        setor = new Setor();
        tabelaSaida();
    }

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed


    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        List<ProdutoPermanente> lista;
        lista = (produtoPermanenteDAO.listar());
        ProdutoPermanenteTableModel itm = new ProdutoPermanenteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Produto Permanente");
        if (objetoRetorno != null) {
            produtoPermanente = produtoPermanenteDAO.consultarObjetoId("idProdutoPermanente", objetoRetorno);
            txtProduto.setText(produtoPermanente.getNomeProdutoPermanente());
            txtProduto.setEnabled(false);
            listaEstoque = estoqueDAO.checkExistseq("produtoPermanente.idProdutoPermanente", produtoPermanente.getIdProdutoPermanente());
            listaEstoque.sort((a, b) -> b.compareTo(a));
            tabelaSaida();
        }
    }//GEN-LAST:event_btnProdutoActionPerformed

    private int capturarLinhaSelecionada() {
        int row = tbSaida.getSelectedRow();
        if (row > -1) {
            return row;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Ítem!",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
    }

    private void btDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolverActionPerformed
        if (capturarLinhaSelecionada() != -1) {
            listaEstoque.get(capturarLinhaSelecionada()).setStatus(false);
            tabelaSaida();
        }
    }//GEN-LAST:event_btDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDevolucaoPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDevolucaoPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDevolucaoPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDevolucaoPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroDevolucaoPermanente dialog = new CadastroDevolucaoPermanente(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDevolver;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btVoltar1;
    private javax.swing.JButton btnProduto;
    private javax.swing.ButtonGroup grupoDestino;
    private javax.swing.JLabel jLObrigatorioNome1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlSaida;
    private javax.swing.JTable tbSaida;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
