/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estocmed.telas;

import estocmed.estoquepermanente.EstoquePermanente;
import estocmed.estoquepermanente.EstoquePermanenteCadastroTableModel;
import estocmed.estoquepermanente.EstoquePermanenteDAO;
import estocmed.estoquepermanente.EstoquePermanenteTableModel;
import estocmed.produtopermanente.ProdutoPermanente;
import estocmed.produtopermanente.ProdutoPermanenteDAO;
import estocmed.produtopermanente.ProdutoPermanenteTableModel;
import estocmed.saidapermanente.SaidaPermanente;
import estocmed.saidapermanente.SaidaPermanenteDAO;
import estocmed.setor.Setor;
import estocmed.setor.SetorDAO;
import estocmed.setor.SetorTableModel;
import estocmed.usuario.Usuario;
import estocmed.util.Util;
import java.awt.Point;
import java.awt.Rectangle;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JViewport;

/**
 *
 * @author Adriano Lima
 */
public class CadastroSaidaPermanente extends javax.swing.JDialog {

    EstoquePermanente estoque = new EstoquePermanente();
    EstoquePermanenteDAO estoqueDAO;
    ProdutoPermanente produtoPermanente = new ProdutoPermanente();
    ProdutoPermanenteDAO produtoPermanenteDAO;
    SetorDAO setorDAO;
    Usuario usuario;
    Setor setor = new Setor();
    SaidaPermanenteDAO saidaDAO;
    List<EstoquePermanente> estoqueAtual;
    SaidaPermanente saidaEstoque = new SaidaPermanente();
    int qtd;
    int rowEstoque;
    private static Object objeto;
    List<EstoquePermanente> listaEstoqueCadastro = new ArrayList<>();

    /**
     * Creates new form TelaCadastroUsuario
     *
     * @param usuario
     */
    public CadastroSaidaPermanente(java.awt.Frame parent, boolean modal, Usuario usuario) {
        initComponents();
        estoqueDAO = new EstoquePermanenteDAO(this.usuario);
        estoqueAtual = estoqueDAO.listar();
        this.usuario = usuario;
        produtoPermanenteDAO = new ProdutoPermanenteDAO(this.usuario);
        saidaDAO = new SaidaPermanenteDAO(this.usuario);
        setorDAO = new SetorDAO(this.usuario);
        txtSetor.setEnabled(false);
        txtProduto.setEnabled(false);
        setModal(true);
    }

    public void tabelaSaida() {
        EstoquePermanenteTableModel tbl = new EstoquePermanenteTableModel(saidaEstoque.getEstoquePermanente());
        tbSaida.setModel(tbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDestino = new javax.swing.ButtonGroup();
        jLObrigatorioNome1 = new javax.swing.JLabel();
        jlSaida = new javax.swing.JLabel();
        jlDestino1 = new javax.swing.JLabel();
        txtSetor = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        jLObrigatorioNome2 = new javax.swing.JLabel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        btnProduto = new javax.swing.JButton();
        btnSetor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSaida = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        btVoltar1 = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 520));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLObrigatorioNome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome1.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome1.setText("*");
        getContentPane().add(jLObrigatorioNome1);
        jLObrigatorioNome1.setBounds(600, 120, 10, 30);

        jlSaida.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlSaida.setText("Saída");
        getContentPane().add(jlSaida);
        jlSaida.setBounds(350, 160, 50, 30);

        jlDestino1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlDestino1.setText("Setor:");
        getContentPane().add(jlDestino1);
        jlDestino1.setBounds(170, 90, 46, 30);

        txtSetor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSetor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtSetor.setMaximumSize(new java.awt.Dimension(8, 200));
        txtSetor.setMinimumSize(new java.awt.Dimension(8, 200));
        txtSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetorActionPerformed(evt);
            }
        });
        getContentPane().add(txtSetor);
        txtSetor.setBounds(220, 90, 380, 30);

        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtProduto.setMaximumSize(new java.awt.Dimension(8, 200));
        txtProduto.setMinimumSize(new java.awt.Dimension(8, 200));
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto);
        txtProduto.setBounds(220, 130, 380, 30);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(710, 190, 80, 70);

        jLObrigatorioNome2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome2.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome2.setText("*");
        getContentPane().add(jLObrigatorioNome2);
        jLObrigatorioNome2.setBounds(600, 90, 10, 10);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Produto:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(150, 130, 70, 30);

        btnProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnProduto.setContentAreaFilled(false);
        btnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto);
        btnProduto.setBounds(610, 130, 30, 30);

        btnSetor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnSetor.setContentAreaFilled(false);
        btnSetor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSetor);
        btnSetor.setBounds(610, 90, 30, 30);

        tbSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSaida);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 190, 670, 220);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(350, 430, 99, 70);

        btVoltar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar1.setText("Voltar");
        btVoltar1.setContentAreaFilled(false);
        btVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar1);
        btVoltar1.setBounds(20, 430, 90, 70);

        btSalvar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/SalvarM.png"))); // NOI18N
        btSalvar1.setText("Salvar");
        btSalvar1.setContentAreaFilled(false);
        btSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar1);
        btSalvar1.setBounds(700, 430, 80, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/SaídaDePermanentes.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(800, 520));
        jLabel6.setMinimumSize(new java.awt.Dimension(800, 520));
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificarEstoque(EstoquePermanente estoque) {
        for (EstoquePermanente estoquePermanente : saidaEstoque.getEstoquePermanente()) {
            if (estoque.getIdEstoquePermanente() == estoquePermanente.getIdEstoquePermanente()) {
                return true;
            }
        }
        return false;
    }

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if (setor.getIdSetor() != 0 && produtoPermanente.getIdProdutoPermanente() != 0) {
            List<EstoquePermanente> lista;
            lista = estoqueDAO.checkExistseq("produtoPermanente.idProdutoPermanente", produtoPermanente.getIdProdutoPermanente());
            EstoquePermanenteTableModel itm = new EstoquePermanenteTableModel(lista);
            Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Estoque");
            if (objetoRetorno != null) {
                estoque = estoqueDAO.consultarObjetoId("idEstoquePermanente", objetoRetorno);
                if (!estoque.isStatus()) {
                    if (!verificarEstoque(estoque)) {
                        estoque.setStatus(true);
                        saidaEstoque.getEstoquePermanente().add(estoque);
                        tabelaSaida();
                    } else {
                        JOptionPane.showMessageDialog(this, "Produto já está na lista!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Produto já está emprestado!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o produto e o setor!");
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltar1ActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        if (!(txtSetor.getText().equals("") && txtProduto.getText().equals(""))) {
            saidaEstoque.setDataSaida(new Date());
            saidaEstoque.setSetor(setor);
            saidaDAO.adicionar(saidaEstoque);
            JOptionPane.showMessageDialog(null, "Saída realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não é possivel fazer a retirada. Selecione Setor e Produto.");
        }
        limparCampos();
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void limparCampos() {
        Util.limparCamposGenerico(this);
        estoque = new EstoquePermanente();
        produtoPermanente = new ProdutoPermanente();
        saidaEstoque = new SaidaPermanente();
        setor = new Setor();
        tabelaSaida();
    }

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed


    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        List<ProdutoPermanente> lista;
        lista = (produtoPermanenteDAO.listar());
        ProdutoPermanenteTableModel itm = new ProdutoPermanenteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Produto Permanente");
        if (objetoRetorno != null) {
            produtoPermanente = produtoPermanenteDAO.consultarObjetoId("idProdutoPermanente", objetoRetorno);
            txtProduto.setText(produtoPermanente.getNomeProdutoPermanente());
            txtProduto.setEnabled(false);
            listaEstoqueCadastro = estoqueDAO.checkExistseq("produtoPermanente.idProdutoPermanente", produtoPermanente.getIdProdutoPermanente());
        }
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        List<Setor> lista;
        lista = (setorDAO.listar());
        SetorTableModel itm = new SetorTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Setor");
        if (objetoRetorno != null) {
            setor = setorDAO.consultarObjetoId("idSetor", objetoRetorno);
            txtSetor.setEnabled(false);
            txtSetor.setText(setor.getNomeSetor());

        }
    }//GEN-LAST:event_btnSetorActionPerformed

    private void txtSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int row = tbSaida.getSelectedRow();
        if (row > -1) {
            saidaEstoque.getEstoquePermanente().remove(row);
            tabelaSaida();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Ítem!",
                "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSaidaPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSaidaPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSaidaPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSaidaPermanente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroSaidaPermanente dialog = new CadastroSaidaPermanente(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btVoltar1;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSetor;
    private javax.swing.ButtonGroup grupoDestino;
    private javax.swing.JLabel jLObrigatorioNome1;
    private javax.swing.JLabel jLObrigatorioNome2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlDestino1;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlSaida;
    private javax.swing.JTable tbSaida;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtSetor;
    // End of variables declaration//GEN-END:variables
}
