/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estocmed.telas;

import estocmed.estoquepermanente.EstoquePermanente;
import estocmed.estoquepermanente.EstoquePermanenteCadastroTableModel;
import estocmed.estoquepermanente.EstoquePermanenteDAO;
import estocmed.fornecedor.Fornecedor;
import estocmed.fornecedor.FornecedorDAO;
import estocmed.produtopermanente.ProdutoPermanente;
import estocmed.produtopermanente.ProdutoPermanenteDAO;
import estocmed.produtopermanente.ProdutoPermanenteTableModel;
import estocmed.usuario.Usuario;
import estocmed.util.LogGeneric;
import estocmed.util.Util;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriano Lima
 */
public class CadastroEstoquePermanente extends javax.swing.JDialog {

    EstoquePermanente estoque;
    EstoquePermanenteDAO estoqueDAO;
    ProdutoPermanente produto = new ProdutoPermanente();
    ProdutoPermanenteDAO produtoDAO;
    Usuario usuario = new Usuario();
    Fornecedor fornecedor = new Fornecedor();
    FornecedorDAO fornecedorDAO;
    List<EstoquePermanente> listaEstoqueCadastro = new ArrayList<>();
    SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form TelaCadastroUsuario
     *
     * @param usuario
     */
    public CadastroEstoquePermanente(java.awt.Frame parent, boolean modal, Usuario usuario) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);
        btLimparActionPerformed(null);
        setModal(true);
        txtProduto.setEnabled(false);
        this.usuario = usuario;
        fornecedorDAO = new FornecedorDAO(this.usuario);
        produtoDAO = new ProdutoPermanenteDAO(this.usuario);
        estoqueDAO = new EstoquePermanenteDAO(this.usuario);
    }

    public void atualizarTabelaEstoque() {
        EstoquePermanenteCadastroTableModel tbCad = new EstoquePermanenteCadastroTableModel(listaEstoqueCadastro);
        tbEstoque.setModel(tbCad);
    }

    public void addProdutos() {

        if (produto != null) {
            InformarDataETombo a = new InformarDataETombo(true);
            a.setVisible(true);
            estoque = new EstoquePermanente();
            estoque.setProdutoPermanente(produto);
            estoque.setDataEntradaPermanente(new Date());
            estoque.setVencimentoPermanente(a.retornarData());
            estoque.setTomboProdutoPermanente(a.retornarTombo());
            listaEstoqueCadastro.add(estoque);
            atualizarTabelaEstoque();
        } else {
            System.out.println("Selecione um produto!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDestino = new javax.swing.ButtonGroup();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstoque = new javax.swing.JTable();
        jlNomeUsuario5 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnProduto2 = new javax.swing.JButton();
        addProdutos = new javax.swing.JButton();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(773, 521));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setDefaultCapable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(30, 430, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(340, 430, 100, 73);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(450, 430, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(240, 430, 80, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/Salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(670, 430, 80, 70);

        tbEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEstoque);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 160, 620, 250);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Produto:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(50, 80, 70, 20);

        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtProduto.setMaximumSize(new java.awt.Dimension(8, 200));
        txtProduto.setMinimumSize(new java.awt.Dimension(8, 200));
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto);
        txtProduto.setBounds(50, 100, 370, 30);

        btnProduto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProduto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnProduto2.setContentAreaFilled(false);
        btnProduto2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProduto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduto2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto2);
        btnProduto2.setBounds(430, 100, 30, 30);

        addProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add40-40.png"))); // NOI18N
        addProdutos.setText("Adicionar");
        addProdutos.setToolTipText("Clique aqui para adicionar um novo estoque do produto selecionado.");
        addProdutos.setContentAreaFilled(false);
        addProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(addProdutos);
        addProdutos.setBounds(660, 160, 100, 80);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(420, 90, 10, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/EstoquePermanente.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(773, 520));
        jLabel6.setMinimumSize(new java.awt.Dimension(773, 520));
        jLabel6.setPreferredSize(new java.awt.Dimension(773, 520));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(2, 0, 770, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        
        if (produto.getIdProdutoPermanente() != 0) {
            //listaEstoqueCadastro = new ArrayList<>();
            listaEstoqueCadastro = estoqueDAO.checkExistseq("produtoPermanente.idProdutoPermanente", produto.getIdProdutoPermanente());
            if (listaEstoqueCadastro != null) {
                atualizarTabelaEstoque();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o produto!");
        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (tbEstoque.getSelectedRow() > -1) {
            if (listaEstoqueCadastro.get(tbEstoque.getSelectedRow()).getIdEstoquePermanente() != 0) {
                estoqueDAO.excluir(listaEstoqueCadastro.get(tbEstoque.getSelectedRow()));
            }
            listaEstoqueCadastro.remove(tbEstoque.getSelectedRow());
            atualizarTabelaEstoque();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um produto!",
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btExcluirActionPerformed


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String estoquesSalvos = "";
        for (EstoquePermanente estoquePermanente : listaEstoqueCadastro) {
            if (estoque.getIdEstoquePermanente() == 0) {
                if (estoqueDAO.salvar(estoquePermanente)) {
                    estoquesSalvos = "PRODUTO: " + estoquePermanente.getProdutoPermanente().getNomeProdutoPermanente()
                            + "   TOMBO: " + estoquePermanente.getTomboProdutoPermanente() + "\n" + estoquesSalvos;
                    produto = new ProdutoPermanente();
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Lista de estoques do produto: " + txtProduto.getText() + "\n\n" + estoquesSalvos);
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void btnProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduto2ActionPerformed
        List<ProdutoPermanente> lista;
        lista = (produtoDAO.listar());
        ProdutoPermanenteTableModel itm = new ProdutoPermanenteTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Produto Permanente");
        if (objetoRetorno != null) {
            produto = produtoDAO.consultarObjetoId("idProdutoPermanente", objetoRetorno);
            txtProduto.setText(produto.getNomeProdutoPermanente());
            txtProduto.setEnabled(false);
            listaEstoqueCadastro = estoqueDAO.checkExistseq("produtoPermanente.idProdutoPermanente", produto.getIdProdutoPermanente());
            atualizarTabelaEstoque();
        }
    }//GEN-LAST:event_btnProduto2ActionPerformed


    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        listaEstoqueCadastro = new ArrayList<>();
        atualizarTabelaEstoque();
        estoque = new EstoquePermanente();
    }//GEN-LAST:event_btLimparActionPerformed

    private void addProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdutosActionPerformed
        addProdutos();
    }//GEN-LAST:event_addProdutosActionPerformed

    private void tbEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEstoqueMouseClicked
        if (evt.getClickCount() == 1) {
            btExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_tbEstoqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoquePermanente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoquePermanente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoquePermanente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstoquePermanente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroEstoquePermanente dialog = new CadastroEstoquePermanente(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProdutos;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnProduto2;
    private javax.swing.ButtonGroup grupoDestino;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JTable tbEstoque;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
