/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estocmed.telas;

import estocmed.curso.Curso;
import estocmed.curso.CursoDAO;
import estocmed.curso.CursoTableModel;
import estocmed.destino.Destino;
import estocmed.estoqueconsumo.EstoqueConsumo;
import estocmed.estoqueconsumo.EstoqueConsumoDAO;
import estocmed.saidaconsumo.SaidaConsumo;
import estocmed.saidaconsumo.SaidaConsumoDAO;
import estocmed.usuario.Usuario;
import estocmed.util.Relatorios;
import estocmed.util.Util;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Karlos
 */
public class RelatorioSaidaEstoqueConsumoVencimentoCurso extends javax.swing.JDialog {

    Usuario usuario;
    EstoqueConsumoDAO estoqueConsumoDAO;
    EstoqueConsumo estoqueConsumo = new EstoqueConsumo();
    Curso curso = new Curso();
    CursoDAO cursoDAO;
    SaidaConsumoDAO saidaDAO = new SaidaConsumoDAO(usuario);

    public RelatorioSaidaEstoqueConsumoVencimentoCurso(boolean modal, Usuario usuario) {
        initComponents();
        getRootPane().setDefaultButton(btPesquisar);
        setModal(true);
        this.usuario = usuario;
        estoqueConsumoDAO = new EstoqueConsumoDAO(this.usuario);
        cursoDAO = new CursoDAO(this.usuario);
        txtCurso.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVoltar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        txtDataInicial = new javax.swing.JFormattedTextField();
        txtDataFinal = new javax.swing.JFormattedTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jlNomeUsuario3 = new javax.swing.JLabel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        btnCurso = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(10, 270, 90, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(150, 270, 80, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(290, 270, 100, 70);

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDataInicial);
        txtDataInicial.setBounds(230, 150, 120, 30);

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDataFinal);
        txtDataFinal.setBounds(230, 210, 120, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Curso:");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(30, 70, 70, 20);

        txtCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtCurso.setMaximumSize(new java.awt.Dimension(8, 200));
        txtCurso.setMinimumSize(new java.awt.Dimension(8, 200));
        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCurso);
        txtCurso.setBounds(30, 90, 320, 30);

        jlNomeUsuario3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario3.setText("Data Vencimento Inicial.:");
        getContentPane().add(jlNomeUsuario3);
        jlNomeUsuario3.setBounds(30, 160, 200, 20);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Data Vencimento Final.:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(30, 220, 180, 20);

        btnCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnCurso.setContentAreaFilled(false);
        btnCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCurso);
        btnCurso.setBounds(350, 90, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/tela de Relatorios.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(400, 350));
        jLabel6.setMinimumSize(new java.awt.Dimension(400, 350));
        jLabel6.setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        curso = new Curso();
    }//GEN-LAST:event_btLimparActionPerformed

    public List ordenarData(List ec) {
        List<EstoqueConsumo> listaEstoque1 = ec;
        List<EstoqueConsumo> listaEstoque2 = ec;
        for (int i = 0; i < ec.size() - 1; i++) {
            for (int j = i + 1; j < ec.size(); j++) {
                if (listaEstoque1.get(i).getVencimentoProdConsumo().after(listaEstoque2.get(j).getVencimentoProdConsumo())) {
                    Collections.swap(listaEstoque1, i, j);
                }
            }
        }
        return listaEstoque1;
    }
    
 
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        List<EstoqueConsumo> estoqueConsumos = new ArrayList<>();
        
        //Instrução para filtrar os dados
        if (txtCurso.getText().equals("") && (txtDataFinal.getText().equals("  /  /    ") && txtDataInicial.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(this, "Campos de pesquisa vazios!");
        } else {
            if (!txtCurso.getText().equals("") && (txtDataFinal.getText().equals("  /  /    ") && txtDataInicial.getText().equals("  /  /    "))) {
                estoqueConsumos = estoqueConsumoDAO.listarRelatorio();
            }else if ((!(txtDataFinal.getText().equals("  /  /    ") || txtDataInicial.getText().equals("  /  /    "))) && txtCurso.getText().equals("")) {
                estoqueConsumos = estoqueConsumoDAO.listaEntreDatas("vencimentoProdConsumo", formataData(txtDataInicial.getText()), formataData(txtDataFinal.getText()));
            }else if (!txtCurso.getText().equals("") && (!(txtDataFinal.getText().equals("  /  /    ") && txtDataInicial.getText().equals("  /  /    ")))) {
                estoqueConsumos = estoqueConsumoDAO.listaEntreDatas("vencimentoProdConsumo", formataData(txtDataInicial.getText()), formataData(txtDataFinal.getText()));
            }
            
            if (!estoqueConsumos.isEmpty()) {
                Relatorios.gerarRelatorioTabelaVencimento(estoqueConsumos);
                curso = new Curso();
                Util.limparCamposGenerico(this);
            } else {
                JOptionPane.showMessageDialog(this, "A pesquisa não encontrou nenhum arquivo!");
                curso = new Curso();
                Util.limparCamposGenerico(this);
            }
        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private Date formataData(String data) {
        if (data == null || data.equals("")) {
            return null;
        }
        Date d = null;
        try {
            DateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
            d = formatar.parse(data);
        } catch (ParseException e) {

        }
        return d;
    }

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        List<Curso> lista;
        lista = (cursoDAO.listar());
        CursoTableModel itm = new CursoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Curso");
        if (objetoRetorno != null) {
            curso = cursoDAO.consultarObjetoId("idCurso", objetoRetorno);
            txtCurso.setText(curso.getNomeCurso());
            txtCurso.setEnabled(false);
        }
    }//GEN-LAST:event_btnCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioSaidaEstoqueConsumoVencimentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioSaidaEstoqueConsumoVencimentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioSaidaEstoqueConsumoVencimentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioSaidaEstoqueConsumoVencimentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioSaidaEstoqueConsumoVencimentoCurso dialog = new RelatorioSaidaEstoqueConsumoVencimentoCurso(true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnCurso;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlNomeUsuario3;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
