/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estocmed.telas;

import estocmed.destino.Destino;
import estocmed.destino.DestinoDAO;
import estocmed.destino.DestinoTableModel;
import estocmed.estoqueconsumo.EstoqueConsumo;
import estocmed.estoqueconsumo.EstoqueConsumoDAO;
import estocmed.saidaconsumo.SaidaConsumo;
import estocmed.saidaconsumo.SaidaConsumoDAO;
import estocmed.usuario.Usuario;
import estocmed.util.Relatorios;
import estocmed.util.Util;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Karlos
 */
public class RelatorioSaidaEstoqueConsumoDestino extends javax.swing.JDialog {

    Usuario usuario;
    EstoqueConsumoDAO estoqueConsumoDAO;
    EstoqueConsumo estoqueConsumo = new EstoqueConsumo();
    Destino destino = new Destino();
    DestinoDAO destinoDAO;
    SaidaConsumo saidaConsumo = new SaidaConsumo();
    SaidaConsumoDAO saidaConsumoDAO;

    public RelatorioSaidaEstoqueConsumoDestino(boolean modal, Usuario usuario) {
        initComponents();
        getRootPane().setDefaultButton(btPesquisar);
        setModal(true);
        this.usuario = usuario;
        estoqueConsumoDAO = new EstoqueConsumoDAO(this.usuario);
        destinoDAO = new DestinoDAO(this.usuario);
        saidaConsumoDAO = new SaidaConsumoDAO(this.usuario);
        txtDestino.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVoltar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        txtDataInicial = new javax.swing.JFormattedTextField();
        jlNomeUsuario3 = new javax.swing.JLabel();
        jlNomeUsuario5 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JFormattedTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        btnSetor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(10, 270, 90, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(150, 270, 80, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(290, 270, 100, 70);

        try {
            txtDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDataInicial);
        txtDataInicial.setBounds(220, 150, 130, 30);

        jlNomeUsuario3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario3.setText("Data de Saída Inicial.:");
        getContentPane().add(jlNomeUsuario3);
        jlNomeUsuario3.setBounds(30, 160, 180, 20);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("Data de Saída Final.:");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(30, 220, 180, 20);

        try {
            txtDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDataFinal);
        txtDataFinal.setBounds(220, 210, 130, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("Destino:");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(30, 70, 70, 20);

        txtDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDestino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 44, 143), 1, true));
        txtDestino.setMaximumSize(new java.awt.Dimension(8, 200));
        txtDestino.setMinimumSize(new java.awt.Dimension(8, 200));
        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestino);
        txtDestino.setBounds(30, 90, 320, 30);

        btnSetor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/add20-20.png"))); // NOI18N
        btnSetor.setContentAreaFilled(false);
        btnSetor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSetor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSetor);
        btnSetor.setBounds(350, 90, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/tela de Relatorios.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(400, 350));
        jLabel6.setMinimumSize(new java.awt.Dimension(400, 350));
        jLabel6.setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        destino = new Destino();
    }//GEN-LAST:event_btLimparActionPerformed


    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<SaidaConsumo> saidas = new ArrayList<>();

        //Instrução para filtrar os dados
        if (txtDestino.getText().equals("") && (txtDataFinal.getText().equals("  /  /    ") && txtDataInicial.getText().equals("  /  /    "))) {
            JOptionPane.showMessageDialog(this, "Campos de pesquisa vazios!");
        } else {
            if (!txtDestino.getText().equals("") && (txtDataFinal.getText().equals("  /  /    ") && txtDataInicial.getText().equals("  /  /    "))) {
                saidas = saidaConsumoDAO.checkExistsRelatorio("destino.idDestino", destino.getIdDestino());

            } else if ((!(txtDataFinal.getText().equals("  /  /    ") || txtDataInicial.getText().equals("  /  /    "))) && txtDestino.getText().equals("")) {
                saidas = saidaConsumoDAO.listaEntreDatas("dataSaida", formataData(txtDataInicial.getText()), formataData(txtDataFinal.getText()));

            } else if (!txtDestino.getText().equals("") && (!(txtDataFinal.getText().equals("  /  /    ") && txtDataInicial.getText().equals("  /  /    ")))) {
                saidas = saidaConsumoDAO.listaEntreDatasECampo("dataSaida",
                        formataData(txtDataInicial.getText()), formataData(txtDataFinal.getText()), "destino.idDestino", destino.getIdDestino());
            }

            if (!saidas.isEmpty()) {
                Relatorios.gerarRelatorioTabelaSaida(saidas);
                destino = new Destino();
                Util.limparCamposGenerico(this);
            } else {
                JOptionPane.showMessageDialog(this, "A pesquisa não encontrou nenhum arquivo!");
                destino = new Destino();
                Util.limparCamposGenerico(this);
            }

        }


    }//GEN-LAST:event_btPesquisarActionPerformed

    private Date formataData(String data) {
        if (data == null || data.equals("")) {
            return null;
        }
        Date d = null;
        try {
            DateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
            d = formatar.parse(data);
        } catch (ParseException e) {

        }
        return d;
    }

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        List<Destino> lista;
        lista = (destinoDAO.listar());
        DestinoTableModel itm = new DestinoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Destino");
        if (objetoRetorno != null) {
            destino = destinoDAO.consultarObjetoId("idDestino", objetoRetorno);
            txtDestino.setText(destino.getNomeDestino());
            txtDestino.setEnabled(false);
        }
    }//GEN-LAST:event_btnSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioSaidaEstoqueConsumoDestino dialog = new RelatorioSaidaEstoqueConsumoDestino(true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btnSetor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlNomeUsuario3;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JFormattedTextField txtDataFinal;
    private javax.swing.JFormattedTextField txtDataInicial;
    private javax.swing.JTextField txtDestino;
    // End of variables declaration//GEN-END:variables
}
